In [31]:
import tensorflow as tf
import pandas as pd

from keras.models import Sequential
from keras.layers import Dense,RepeatVector
from keras.layers import Flatten
from keras.layers import TimeDistributed

## Data Loading

In [20]:
# USE THIS PATH FOR WINDOWS
#biomass_history = pd.read_csv('dataset\Biomass_History.csv')
# PATH FOR LINUX
biomass_history = pd.read_csv('dataset/Biomass_History.csv')

In [21]:
biomass_history.head(20)

,Index,Latitude,Longitude,2010,2011,2012,2013,2014,2015,2016,2017
0,0,24.66818,71.33144,8.475744,8.868568,9.202181,6.023070,10.788374,6.647325,7.387925,5.180296
1,1,24.66818,71.41106,24.029778,28.551348,25.866415,21.634459,34.419411,27.361908,40.431847,42.126945
2,2,24.66818,71.49069,44.831635,66.111168,56.982258,53.003735,70.917908,42.517117,59.181629,73.203232
3,3,24.66818,71.57031,59.974419,80.821304,78.956543,63.160561,93.513924,70.203171,74.536720,101.067352
4,4,24.66818,71.64994,14.653370,19.327524,21.928144,17.899586,19.534035,19.165791,16.531315,26.086885
5,5,24.66818,71.72956,17.416639,35.811001,26.003826,27.348482,29.599268,22.026114,23.592617,41.749001
6,6,24.66818,71.80919,23.568657,37.371216,38.298550,27.838022,40.779961,32.014874,37.771797,55.003929
7,7,24.66818,71.88882,48.345234,91.215836,91.906342,41.121754,57.266411,60.263412,72.291153,29.411613
8,8,24.66818,71.96844,58.784283,50.206898,60.707321,37.598999,59.462139,38.788315,31.312796,37.497009
9,9,24.66818,72.04807,67.907379,68.375999,87.026680,54.602242,78.118126,44.796188,36.008152,52.549976
10,10,24.66818,72.12769,8.916524,16.679886,21.618805,13.550439,15.403367,7.133225,7.732000,9.861409
11,11,24.66818,72.20732,3.416374,2.891346,3.826416,3.098782,6.333014,4.840425,4.729421,7.909709
12,12,24.66818,72.28694,2.298106,2.165051,1.780242,2.644897,5.368379,4.423479,4.019220,7.005911
13,13,24.66818,72.36657,0.405264,0.146914,0.168368,0.251683,0.180468,0.131804,0.170856,0.177587
14,14,24.58758,71.25181,0.378064,1.557208,0.267738,0.703204,0.319150,0.268468,0.407948,0.952279
15,15,24.58758,71.33144,45.174110,67.934845,58.226315,35.267220,55.589840,34.768570,29.412724,26.509066
16,16,24.58758,71.41106,56.539742,83.333382,81.218788,59.407043,85.440163,78.999176,94.716049,85.237656
17,17,24.58758,71.49069,139.388947,161.756607,149.984787,132.148621,205.142639,130.579208,128.607407,153.976090
18,18,24.58758,71.57031,140.025986,143.676621,105.671814,105.944908,175.587204,114.893639,119.686356,167.433884
19,19,24.58758,71.64994,51.762608,91.464401,90.009483,58.497116,83.193336,64.630905,60.418457,89.419334

In [22]:
biomass_history.describe()

,Index,Latitude,Longitude,2010,2011,2012,2013,2014,2015,2016,2017
count,2418.000000,2418.000000,2418.000000,2418.000000,2418.000000,2418.000000,2418.000000,2418.000000,2418.000000,2418.000000,2418.000000
mean,1208.500000,22.506537,71.826215,144.401424,150.860247,109.468899,161.886430,157.954024,132.898633,113.089323,159.163367
std,698.160798,1.034936,1.389804,146.506351,142.264612,110.249714,180.337708,139.870466,129.689111,102.092570,158.993069
min,0.000000,20.154560,68.624190,0.000167,0.000433,0.000290,0.000532,0.000155,0.000072,0.000151,0.000191
25%,604.250000,21.685970,70.774060,23.449163,25.576084,22.711070,27.044554,31.514698,22.732275,22.658495,26.064368
50%,1208.500000,22.491970,71.888820,112.298855,126.291077,82.271317,117.662296,136.859337,106.789989,91.721931,120.519817
75%,1812.750000,23.297970,73.003570,207.689327,226.197079,163.512547,222.835739,241.965115,196.102222,177.136295,231.067348
max,2417.000000,24.668180,74.436820,883.691711,771.061646,871.800415,1232.853760,871.800415,771.061646,514.148987,883.691711

In [23]:
biomass_history.shape

(2418, 11)

In [26]:
tf.keras.layers.Conv1D
model = Sequential()

2023-08-19 20:30:42.307058: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 4279 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6